database:
    postgres:
        db_name: mytestdb
        username: postgres
        password: Friday
        port: 5432
        dialect: postgresql
        host: localhost
    mysql:
        db_name: menagerie
        username: root
        password: Monday
        port: 3306
        dialect: pymysql
        host: localhost
    mongo:
        db_name: films
        username: root
        password: Monday
        port: 27017
        dialect: mongodb
        host: localhost

